%sheikh wasimuddin lab 8 CSEIOT61 
clc;
clear;
close all;
RSSI0=-42;
n=2.1;
A=[1 3];
B=[11 4];
C=[6 12];
actual=[7 6];
d1a=sqrt((actual(1)-A(1))^2+(actual(2)-A(2))^2);
d2a=sqrt((actual(1)-B(1))^2+(actual(2)-B(2))^2);
d3a=sqrt((actual(1)-C(1))^2+(actual(2)-C(2))^2);
RSSI1=RSSI0-10*n*log10(d1a);
RSSI2=RSSI0-10*n*log10(d2a);
RSSI3=RSSI0-10*n*log10(d3a);
rng(27);
noise=0.7;
RSSI1=RSSI1+noise*randn;
RSSI2=RSSI2+noise*randn;
RSSI3=RSSI3+noise*randn;
d1=10^((RSSI0-RSSI1)/(10*n));
d2=10^((RSSI0-RSSI2)/(10*n));
d3=10^((RSSI0-RSSI3)/(10*n));
M=2*[B(1)-A(1),B(2)-A(2);C(1)-A(1),C(2)-A(2)];
N=[d1^2-d2^2+B(1)^2-A(1)^2+B(2)^2-A(2)^2;d1^2-d3^2+C(1)^2-A(1)^2+C(2)^2-A(2)^2];
estimated=M\N;
x=estimated(1);
y=estimated(2);
error=sqrt((x-actual(1))^2+(y-actual(2))^2);
fprintf('RSSI Based Sensor Node Localization\n');
fprintf('Anchor A RSSI: %.2f dBm Distance: %.2f m\n',RSSI1,d1);
fprintf('Anchor B RSSI: %.2f dBm Distance: %.2f m\n',RSSI2,d2);
fprintf('Anchor C RSSI: %.2f dBm Distance: %.2f m\n',RSSI3,d3);
fprintf('Actual Position: (%.2f,%.2f) m\n',actual(1),actual(2));
fprintf('Estimated Position: (%.2f,%.2f) m\n',x,y);
fprintf('Localization Error: %.2f m\n',error);
theta=linspace(0,2*pi,300);
figure('Color','w','Position',[150 100 900 650]);
hold on;
grid on;
axis equal;
xlim([-1 13]);
ylim([-1 13]);
plot(A(1)+d1*cos(theta),A(2)+d1*sin(theta),'--','LineWidth',1.3);
plot(B(1)+d2*cos(theta),B(2)+d2*sin(theta),'--','LineWidth',1.3);
plot(C(1)+d3*cos(theta),C(2)+d3*sin(theta),'--','LineWidth',1.3);
plot(A(1),A(2),'s','MarkerSize',12,'MarkerFaceColor','r','MarkerEdgeColor','k','LineWidth',1.5);
plot(B(1),B(2),'s','MarkerSize',12,'MarkerFaceColor','r','MarkerEdgeColor','k','LineWidth',1.5);
plot(C(1),C(2),'s','MarkerSize',12,'MarkerFaceColor','r','MarkerEdgeColor','k','LineWidth',1.5);
plot(actual(1),actual(2),'o','MarkerSize',14,'MarkerFaceColor','b','MarkerEdgeColor','k','LineWidth',1.5);
plot(x,y,'d','MarkerSize',13,'MarkerFaceColor','g','MarkerEdgeColor','k','LineWidth',1.5);
plot([actual(1) x],[actual(2) y],'k-.','LineWidth',1.5);
text(A(1)+0.3,A(2)-0.6,'Anchor A','FontSize',11,'FontWeight','bold');
text(B(1)+0.3,B(2)-0.6,'Anchor B','FontSize',11,'FontWeight','bold');
text(C(1)+0.3,C(2)+0.2,'Anchor C','FontSize',11,'FontWeight','bold');
text(actual(1)+0.3,actual(2)+0.2,'Actual Sensor','FontSize',11,'FontWeight','bold');
text(x+0.3,y-0.5,'Estimated Sensor','FontSize',11,'FontWeight','bold');
xlabel('X Coordinate (m)','FontSize',12,'FontWeight','bold');
ylabel('Y Coordinate (m)','FontSize',12,'FontWeight','bold');
title('RSSI Sensor Node Localization','FontSize',15,'FontWeight','bold');
legend('RSSI Range A','RSSI Range B','RSSI Range C','Anchor Nodes','Actual Position','Estimated Position','Location','northwest');
text(0,12.3,sprintf('Localization Error = %.2f m',error),'FontSize',11,'FontWeight','bold');
hold off;
